export const LEVEL_INFO = [
  { level: 1, title: 'Level 1', tagline: 'Everyone gets these. Kids, parents, spectators.' },
  { level: 2, title: 'Level 2', tagline: 'Pony clubbers and horsey parents should manage these.' },
  { level: 3, title: 'Level 3', tagline: 'Real riding knowledge plus the basics every competitor should know.' },
  { level: 4, title: 'Level 4', tagline: 'Things a regular competitor should know from actually showing.' },
  { level: 5, title: 'Level 5', tagline: 'Hard — the kind where people kick themselves afterwards.' },
];

export const QUESTIONS = {
  1: [
    { q: "What do you call a baby horse?", a: "A foal" },
    { q: "What is a female horse called?", a: "A mare" },
    { q: "What is an adult male horse that has not been castrated called?", a: "A stallion" },
    { q: "What is a castrated male horse called?", a: "A gelding" },
    { q: "What do horses wear on their feet?", a: "Horseshoes" },
    { q: "What is the long hair on a horse's neck called?", a: "The mane" },
    { q: "What do you sit on when you ride?", a: "A saddle" },
    { q: "What do you hold to steer the horse?", a: "The reins" },
    { q: "What is the hard part of a horse's foot called?", a: "The hoof" },
    { q: "What must every rider wear on their head at a SAWMGA show?", a: "A helmet" },
    { q: "True or false: horses can sleep standing up.", a: "True" },
    { q: "What do horses mainly eat?", a: "Grass and hay" },
    { q: "Which end of the horse should you never stand directly behind?", a: "The back end" },
    { q: "What is a group of horses called?", a: "A herd" },
    { q: "What is the orange crunchy treat horses love?", a: "A carrot" },
    { q: "What unit do we measure a horse's height in?", a: "Hands" },
    { q: "What is a young female horse under four called?", a: "A filly" },
    { q: "What is a young male horse under four called?", a: "A colt" },
    { q: "In Western Mounted Games, do you ride Western or English?", a: "Western" },
    { q: "What is the metal piece that goes in the horse's mouth called?", a: "The bit" },
  ],
  2: [
    { q: "What is the fastest gait of a horse?", a: "The gallop" },
    { q: "Name the four natural gaits.", a: "Walk, trot, canter, gallop" },
    { q: "How many inches are in one hand?", a: "Four" },
    { q: "What does SAWMGA stand for?", a: "South African Western Mounted Games Association" },
    { q: "How many barrels are used in the Barrel Race?", a: "Three" },
    { q: "How many poles are used in Pole Bending I?", a: "Six" },
    { q: "What is the person who shoes horses called?", a: "A farrier" },
    { q: "What is a palomino?", a: "A golden or cream coat with a white mane and tail" },
    { q: "What is a chestnut horse?", a: "Reddish brown with a mane and tail the same colour" },
    { q: "What tool is used to clean out a horse's hooves?", a: "A hoof pick" },
    { q: "What is the strap under the belly that holds a Western saddle on?", a: "The cinch" },
    { q: "What goes under the saddle to protect the horse's back?", a: "A saddle pad or blanket" },
    { q: "What is a wide white marking down the middle of the face called?", a: "A blaze" },
    { q: "In Speed Ball, what kind of ball must be used?", a: "A standard golf ball" },
    { q: "How many events does SAWMGA have in total?", a: "Thirteen" },
    { q: "How many games are run at a provincial qualifier?", a: "Five" },
    { q: "What colour ribbon must a stallion wear in its tail?", a: "Yellow" },
    { q: "What colour ribbon marks a horse that kicks?", a: "Red" },
    { q: "Which striped animal is a close relative of the horse?", a: "The zebra" },
    { q: "In the Keyhole, what must all four of the horse's feet do?", a: "Enter the circle" },
  ],
  3: [
    { q: "What is the frog?", a: "The V shaped structure on the underside of the hoof" },
    { q: "Where exactly is a horse's height measured from?", a: "The withers to the ground" },
    { q: "What are the withers?", a: "The ridge at the base of the neck between the shoulder blades" },
    { q: "What is the minimum age for a horse to compete at a SAWMGA show?", a: "Three years old" },
    { q: "How many runs does a rider get at each event, and which one counts?", a: "Two runs, the best time counts" },
    { q: "What is the maximum time allowed to complete a course before a No Time?", a: "120 seconds" },
    { q: "What is the standard penalty for knocking down or dislodging a pole?", a: "Two seconds" },
    { q: "What is the penalty for knocking down a barrel in the Barrel Race?", a: "Five seconds" },
    { q: "Name the four SAWMGA age categories.", a: "Child, Junior, Senior, Veteran" },
    { q: "On what date is a rider's age determined for the year?", a: "1 January of the current year" },
    { q: "What flag does the judge use to open the course?", a: "A white flag held straight up in the air" },
    { q: "What flag signals a No Time or disqualification?", a: "A red flag, swung low and horizontally" },
    { q: "What is colic?", a: "Abdominal pain, a medical emergency in horses" },
    { q: "What is laminitis?", a: "Inflammation of the sensitive laminae inside the hoof" },
    { q: "Which breed dominates Western sport and is known for sprinting the quarter mile?", a: "The Quarter Horse" },
    { q: "What is a bay horse?", a: "A brown or reddish body with black points" },
    { q: "What is the main difference between a snaffle and a curb bit?", a: "A snaffle works on direct pressure, a curb has shanks and works on leverage" },
    { q: "What is a \"lead\" at canter?", a: "Which foreleg reaches further forward in the stride" },
    { q: "How long is a mare's gestation period?", a: "About eleven months" },
    { q: "Which insect borne disease do South African horses get vaccinated against annually?", a: "African Horse Sickness" },
  ],
  4: [
    { q: "Name eight of the thirteen SAWMGA events.", a: "Any eight of: Barrel Race, Big T, Birangle, Figure 8 Flag, Figure 8 Stake, Hurry Scurry, Keyhole, Pole Bending I, Pole Bending II, Quadrangle Stake, Speed Ball, Speed Barrels, Single Stake" },
    { q: "How far from the timing line is the running start?", a: "24.4 metres" },
    { q: "What happens if you knock over a bucket in Figure 8 Flag?", a: "Disqualified" },
    { q: "What happens if the flag touches the ground in Figure 8 Flag?", a: "Disqualified" },
    { q: "What happens in Speed Ball if the golf ball does not end up inside the cone?", a: "No Time" },
    { q: "What must be signed before anyone may ride a stallion at a SAWMGA show?", a: "A Stallion Indemnity Form" },
    { q: "May a mare with a foal at foot compete?", a: "No, and neither may a mare four months or more pregnant" },
    { q: "What document must a horse have to enter a SAWMGA sanctioned show?", a: "An up to date SAEF horse passport" },
    { q: "How long does a rider have to enter the arena after being notified?", a: "One minute" },
    { q: "Explain the overcount principle.", a: "Achieving a time one level better than your current level counts as an overcount of one, two levels better counts as an overcount of two, and so on" },
    { q: "How many of the thirteen events must you complete with the same horse-rider combination to be eligible for team selection?", a: "No less than eleven" },
    { q: "How many qualifiers must you compete in, in the province where you want to be selected?", a: "At least two" },
    { q: "What is the penalty for competing with attire or equipment in violation of the rules?", a: "One second added" },
    { q: "What score is awarded on the combined Provincial Scoresheet for a game where a double NT was achieved?", a: "200 seconds" },
    { q: "Are draw reins allowed in the arena?", a: "No, they are forbidden except at prize givings and march past parades" },
    { q: "Are blinkers or fly masks allowed?", a: "No, anything restricting the horse's vision is forbidden" },
    { q: "Can the same horse be entered twice in the same event?", a: "No, except as a Lead Line entry" },
    { q: "What is the maximum length of a crop, including the flap?", a: "75 cm" },
    { q: "Which insect spreads African Horse Sickness?", a: "Midges" },
    { q: "What is the average lifespan of a horse?", a: "Roughly 25 to 30 years" },
  ],
  5: [
    { q: "According to the rulebook, which animals does the word \"horse\" include?", a: "All equines, including horses, ponies, donkeys and mules", stumper: true },
    { q: "How does the judge signal that a clean round had penalties rather than none?", a: "Swings the white flag horizontally, left to right, under the shoulder", stumper: true },
    { q: "How does the judge signal a pattern break?", a: "Red flag, while showing a figure of eight with the hand, fingers pointing down", stumper: true },
    { q: "What is the minimum age to take part in the Rescue Race?", a: "12 years old as of 1 January of the current year", stumper: true },
    { q: "Name two things that disqualify a team in the Ribbon Race.", a: "Any two of: dropping either end of the ribbon, breaking it, or holding or locking hands", stumper: true },
    { q: "Which is the only event Lead Line riders may take part in, and how is it set up?", a: "Hurry Scurry, with the poles lying flat on the ground", stumper: true },
    { q: "What is the fastest a Lead Line rider may go before being disqualified?", a: "A trot", stumper: true },
    { q: "In Pole Bending II, what happens if you break the time line while on course?", a: "Disqualification, No Time", stumper: true },
    { q: "In Hurry Scurry, what happens if all three jumping poles are knocked down?", a: "Disqualification", stumper: true },
    { q: "What is the pole spacing in Pole Bending I compared to Pole Bending II?", a: "6.1 m in Poles I, 6.4 m in Poles II", stumper: true },
    { q: "What are the Hurry Scurry jump heights for Levels 0 and 1, compared to Level 2 and up?", a: "30 cm and 45 cm", stumper: true },
    { q: "What makes an obstacle \"dislodged\" rather than knocked down?", a: "It has been moved more than its base width while still standing upright", stumper: true },
    { q: "How is a tie broken in a SAWMGA event?", a: "The rider with the most first places wins, then most second places, and so on", stumper: true },
    { q: "Can show management overrule a judge's ruling?", a: "No, under no circumstances", stumper: true },
    { q: "How many vertebrae are in a horse's neck?", a: "Seven, the same as a human", stumper: true },
    { q: "Why can a horse not vomit?", a: "A very strong sphincter at the stomach entrance plus the angle the oesophagus enters at", stumper: true },
    { q: "What is the scientific name of the domestic horse?", a: "Equus ferus caballus", stumper: true },
    { q: "Which is the last surviving truly wild horse species?", a: "Przewalski's horse", stumper: true },
    { q: "Roughly how many bones does a horse have?", a: "About 205", stumper: true },
    { q: "In what year was the AQHA founded?", a: "1940", stumper: true },
  ],
};

export const BONUS_TIEBREAKERS = [
  { q: "Which single event determines the minimum arena size, and why?", a: "The Barrel Race, because it is the largest SAWMGA course." },
  { q: "Which five games make up Qualifier 1 and 7?", a: "Figure 8 Flags, Hurry Scurry, Birangle, Quadrangle, Single Stake." },
  { q: "Which is the only SAWMGA event where the penalty is five seconds rather than two?", a: "The Barrel Race." },
  { q: "Closest guess wins: how many horses competed at the last SAWMGA Nationals?", a: "Open-ended — closest guess to the real number takes it." },
];
